// ============================================================
// ERROR CODES
// Machine-readable error codes for consistent error handling
// across frontend and backend.
// ============================================================

export const ErrorCodes = {
  // Input validation
  INVALID_INPUT: 'INVALID_INPUT',
  INVALID_URL: 'INVALID_URL',

  // Auth
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  USER_EXISTS: 'USER_EXISTS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',

  // Kit
  KIT_NOT_FOUND: 'KIT_NOT_FOUND',
  KIT_NOT_READY: 'KIT_NOT_READY',
  KIT_ALREADY_RUNNING: 'KIT_ALREADY_RUNNING',
  KIT_VALIDATION_FAILED: 'KIT_VALIDATION_FAILED',
  GENERATION_FAILED: 'GENERATION_FAILED',
  CONCURRENT_UPDATE: 'CONCURRENT_UPDATE',


  // Company / crawling
  COMPANY_URL_INVALID: 'COMPANY_URL_INVALID',
  COMPANY_UNREACHABLE: 'COMPANY_UNREACHABLE',
  COMPANY_TIMEOUT: 'COMPANY_TIMEOUT',
  ROBOTS_DENIED: 'ROBOTS_DENIED',
  CONTENT_TYPE_UNSUPPORTED: 'CONTENT_TYPE_UNSUPPORTED',
  SSRF_BLOCKED: 'SSRF_BLOCKED',
  REDIRECT_UNSAFE: 'REDIRECT_UNSAFE',

  // LLM
  LLM_RATE_LIMITED: 'LLM_RATE_LIMITED',
  LLM_INVALID_OUTPUT: 'LLM_INVALID_OUTPUT',
  LLM_PROVIDER_ERROR: 'LLM_PROVIDER_ERROR',

  // Question / flashcard
  QUESTION_NOT_FOUND: 'QUESTION_NOT_FOUND',
  FLASHCARD_NOT_FOUND: 'FLASHCARD_NOT_FOUND',

  // Generic
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  RATE_LIMITED: 'RATE_LIMITED',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
